# Site settings
title: born2roll.org 
email: david@townsendclark.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website for Clark Matthews.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://townsendclark.github.io/born2roll.org" # the base hostname & protocol for your site
twitter_username: Born2rollmc
github_username:  davidtnc

# Build settings
markdown: kramdown
